name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  php:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.2', '8.3', '8.4']
    name: PHP ${{ matrix.php }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction --no-progress

      - name: Run tests
        run: composer test

      - name: Static analysis
        run: composer analyse

  js:
    runs-on: ubuntu-latest
    name: TypeScript
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - run: npm install

      - run: npm run types:check

      - run: npm run format:check
